import {
  Props,
  VNode,
  VNodeChild,
  VNodeChildren,
  flattenChildren,
  isEmptyVNode,
  isTextVNode,
  isValidElement,
} from "./jsx.js";
import { ContextProvider } from "./context.js";
import { EffectTiming, HookState, setHookState } from "./hooks.js";
import { diffElementProps } from "./dom-props.js";

/**
 * Backing object for a rendered vnode.
 *
 * This tracks the last vnode that was rendered, the children (for a DOM component)
 * or output (for a custom component) and the DOM node.
 *
 * `BaseComponent` contains only the basic structure of the rendered tree.
 * It does not include information about internal state of components or pre-computed
 * pointers/flags etc. that are used internally by the renderer.
 */
export interface BaseComponent {
  /** The vnode that produced this component. */
  vnode: VNodeChild;

  /**
   * For DOM components, the child components generated by rendering the DOM vnode's
   * children.
   *
   * For custom components, the child components generated by rendering the
   * component's output.
   *
   * For empty or text components this is not used.
   */
  output: Component[];

  /**
   * DOM node produced by rendering `vnode`.
   */
  dom: Element | Text | null;
}

/**
 * Backing tree for a rendered vnode.
 */
interface Component extends BaseComponent {
  /**
   * The parent component. This is not set on the root component or the
   * empty component.
   */
  parent: Component | null;

  /** The depth of the component from the root. Not set on the empty component. */
  depth: number;

  /**
   * Lazily-allocated hook data for component. This is only set for components
   * that use hooks.
   */
  hooks: HookState | null;

  /**
   * The context data that this component exposes to its descendants.
   */
  contextProvider: ContextProvider<any> | null;

  /** Whether this component is an `<svg>` DOM component or a child of one. */
  svg: boolean;
}

/**
 * The component instance that represents all empty vnodes.
 */
const emptyComponent: Component = Object.freeze({
  parent: null,
  depth: -1,
  vnode: null,
  output: [],
  dom: null,
  hooks: null,
  contextProvider: null,
  svg: false,
});

function vnodeKey(vnode: any) {
  return isValidElement(vnode) ? vnode.key : null;
}

interface ErrorBoundaryProps extends Props {
  handler: (e: Error) => void;
}

interface ErrorBoundaryVNode extends VNode {
  props: ErrorBoundaryProps;
}

export function ErrorBoundary({ children }: ErrorBoundaryProps) {
  return children;
}

function isErrorBoundary(vnode: VNodeChild): vnode is ErrorBoundaryVNode {
  return isValidElement(vnode) && vnode.type === ErrorBoundary;
}

/**
 * Return the top-level DOM nodes rendered by a component.
 */
export function forEachDomRoot(
  c: BaseComponent,
  visit: (node: Element | Text) => void
) {
  if (c.dom) {
    visit(c.dom);
  } else {
    for (let child of c.output) {
      forEachDomRoot(child, visit);
    }
  }
}

function lastDomChild(c: Component): Element | Text | null {
  let node = c.dom;
  for (let i = c.output.length - 1; i >= 0 && !node; i--) {
    node = lastDomChild(c.output[i]);
  }
  return node;
}

const SVG_NAMESPACE = "http://www.w3.org/2000/svg";

const activeRoots = new Map<Element, Root>();

interface RenderError {
  error: Error;
  handled: boolean;
}

function insertNodeAfter(node: Node, parent: Element, after: Node | null) {
  const before = after ? after.nextSibling : parent.firstChild;

  // Calling `parent.insertBefore` has overhead and side effects (eg. causing
  // the element to lose focus) even if the node would logically be positioned
  // in the same place afterwards, so only call if necessary.
  if (
    node.parentNode !== parent ||
    (node !== before && node.nextSibling !== before)
  ) {
    parent.insertBefore(node, before);
  }
}

/**
 * Render tree root.
 *
 * There is one `Root` per DOM subtree rendered by UReact. It is created
 * automatically when `render` is called with a given DOM element container
 * for the first time.
 */
class Root {
  /** The DOM element into which this root renders. */
  container: Element;

  /** The root component produced by the most recent render. */
  private _rootComponent: Component | null;

  /** The DOM `Document` to which `container` belongs. */
  private _document: Document;

  /** Components which have pending effects that need to be executed. */
  private _pendingEffects: Set<Component>;

  /** Components which have pending layout effects that need to be executed. */
  private _pendingLayoutEffects: Set<Component>;

  /** Components that need to be re-rendered due to state updates. */
  private _pendingUpdate: Set<Component>;

  /**
   * Error thrown during the current render or other invocation of user code
   * which has not yet been handled.
   */
  private _currentError: RenderError | null;

  /** Component which is currently being rendered. */
  private _rendering: Component | null;

  /** Create or return the hook data for the currently-rendering component. */
  private _getHookState: () => HookState;

  /**
   * Create a root which renders into `container`.
   */
  constructor(container: Element) {
    this.container = container;

    this._rootComponent = null;
    this._document = container.ownerDocument;
    this._pendingEffects = new Set();
    this._pendingLayoutEffects = new Set();
    this._pendingUpdate = new Set();
    this._currentError = null;
    this._rendering = null;

    this._getHookState = () => {
      const component = this._rendering!;
      if (component.hooks) {
        return component.hooks;
      }

      component.hooks = new HookState({
        scheduleUpdate: () => this._scheduleUpdate(component),
        scheduleEffects: (when) => this._scheduleEffects(component, when),
        getContext: (type) => this._getContext(component, type),
        registerContext: (provider) => (component.contextProvider = provider),
      });
      return component.hooks;
    };

    activeRoots.set(container, this);
  }

  /**
   * Remove all of the rendered DOM nodes from the current tree and run any
   * cleanup associated with components (eg. effect cleanup callbacks).
   */
  unmount() {
    this.render(null);
    activeRoots.delete(this.container);
  }

  /**
   * Update the component tree rendered into this root's container to match
   * `vnode`.
   */
  render(vnode: VNodeChild) {
    this._rootComponent = this._diff(
      null,
      this._rootComponent,
      vnode,
      this.container,
      null
    );

    this._handlePendingError();
  }

  /**
   * Flush all pending state updates and effects.
   */
  flush() {
    while (
      this._pendingUpdate.size > 0 ||
      this._pendingLayoutEffects.size > 0 ||
      this._pendingEffects.size > 0
    ) {
      this._flushUpdates();
      this._flushLayoutEffects();
      this._flushEffects();
    }
  }

  getOutput(): BaseComponent | null {
    return this._rootComponent;
  }

  /**
   * Create or update a component to match a `vnode`.
   *
   * `component` is the existing component to update or `null` if there is no
   * such component. `vnode` is the new vnode value. `parent` and `insertAfter`
   * specify where to insert any new DOM nodes created in the process.
   */
  _diff(
    parentComponent: Component | null,
    component: Component | null,
    vnode: VNodeChild,
    parent: Element,
    insertAfter: Node | null
  ): Component {
    // Update the existing component if there is one and the types match.
    if (component) {
      const prevVnode = component.vnode;
      if (prevVnode === vnode && !this._pendingUpdate.has(component)) {
        // Bail out if vnode is same as previous render, unless there is a pending
        // state update for this component.
        return component;
      }

      let typeMatched = false;

      if (isTextVNode(prevVnode) && isTextVNode(vnode)) {
        if (vnode !== prevVnode) {
          (component.dom as Text).data = vnode.toString();
        }
        typeMatched = true;
      } else if (isEmptyVNode(prevVnode) && isEmptyVNode(vnode)) {
        typeMatched = true;
      } else if (
        isValidElement(prevVnode) &&
        isValidElement(vnode) &&
        prevVnode.type === vnode.type
      ) {
        if (typeof vnode.type === "string") {
          const el = component.dom as Element;
          diffElementProps(el, prevVnode.props, vnode.props);
          component.output = this._diffOutput(
            component,
            component.output,
            vnode.props.children ?? null,
            el,
            null
          );
        } else if (typeof vnode.type === "function") {
          const output = this._renderCustom(vnode, component);
          component.output = this._diffOutput(
            component,
            component.output,
            output,
            parent,
            insertAfter
          );
        }
        typeMatched = true;
      }

      if (typeMatched) {
        if (!isEmptyVNode(vnode)) {
          component.vnode = vnode;
        }
        return component;
      } else {
        this._unmount(component);
      }
    }

    // If there is no existing component or it has a different type, render it
    // from scratch.
    const newComponent = this._renderTree(parentComponent ?? null, vnode);
    forEachDomRoot(newComponent, (node) => {
      insertNodeAfter(node, parent, insertAfter);
      insertAfter = node;
    });
    return newComponent;
  }

  /**
   * Update the output of a component to match `vnodes`.
   *
   * The output of a DOM component is just the component's children. The output
   * of a custom component is the result of calling it with the current props.
   *
   * Note that `prevOutput` is modified as the new output is processed.
   *
   * Returns the new output for the component.
   */
  _diffOutput(
    parentComponent: Component | null,
    prevOutput: Component[],
    vnodes: VNodeChildren,
    parentElement: Element,
    insertAfter: Node | null
  ): Component[] {
    const newOutput = [];

    if (vnodes) {
      for (let child of flattenChildren(vnodes)) {
        // Find the child from the previous render that corresponds to this
        // child.
        const childKey = vnodeKey(child);
        const prevComponentIndex = prevOutput.findIndex(
          (o) => vnodeKey(o.vnode) === childKey
        );

        // Diff the child against the previous matching output, if any.
        const prevComponent =
          prevComponentIndex !== -1 ? prevOutput[prevComponentIndex] : null;
        let childComponent;
        if (prevComponent) {
          // Remove the matched component from `prevOutput`, so that at the end
          // we are left with a list of non-matched items.
          prevOutput.splice(prevComponentIndex, 1);

          childComponent = this._diff(
            parentComponent,
            prevComponent,
            child,
            parentElement,
            insertAfter
          );
        } else {
          childComponent = this._renderTree(parentComponent, child);
        }

        // Ensure the output is in the correct position in the DOM.
        forEachDomRoot(childComponent, (node) => {
          insertNodeAfter(node, parentElement, insertAfter);
          insertAfter = node;
        });

        newOutput.push(childComponent);
      }
    }

    // Remove all the output from the previous render which was not matched
    // against output from the new render.
    for (let unmatched of prevOutput) {
      this._unmount(unmatched);
    }

    return newOutput;
  }

  /**
   * Render a new component tree described by `vnode`.
   */
  _renderTree(parent: Component | null, vnode: VNodeChild): Component {
    if (isEmptyVNode(vnode)) {
      return emptyComponent;
    }

    const newComponent: Component = {
      parent,
      depth: parent ? parent.depth + 1 : 0,
      vnode,
      output: [],
      dom: null,
      hooks: null,
      contextProvider: null,
      svg: parent ? parent.svg : false,
    };

    if (isTextVNode(vnode)) {
      newComponent.dom = this._document.createTextNode(vnode.toString());
    } else if (!isValidElement(vnode)) {
      throw new Error("Object is not a valid element");
    } else if (typeof vnode.type === "string") {
      newComponent.svg = newComponent.svg || vnode.type === "svg";
      const element = newComponent.svg
        ? this._document.createElementNS(SVG_NAMESPACE, vnode.type)
        : this._document.createElement(vnode.type);
      diffElementProps(element, {}, vnode.props);
      if (vnode.ref) {
        vnode.ref.current = element;
      }
      newComponent.dom = element;

      if (vnode.props.children != null) {
        for (let child of flattenChildren(vnode.props.children)) {
          const childComponent = this._renderTree(newComponent, child);
          newComponent.output.push(childComponent);
          forEachDomRoot(childComponent, (node) => element.append(node));
        }
      }
    } else if (typeof vnode.type === "function") {
      const output = this._renderCustom(vnode, newComponent);
      for (let child of flattenChildren(output)) {
        newComponent.output.push(this._renderTree(newComponent, child));
      }
    }

    return newComponent;
  }

  /**
   * Return the ancestor of `component` which provides context of a given `type`.
   */
  _getContext(component: Component, type: any) {
    let parent = component.parent;
    while (parent) {
      if (parent.contextProvider?.type === type) {
        return parent.contextProvider!;
      }
      parent = parent.parent;
    }
    return null;
  }

  _renderCustom(vnode: VNode, component: Component) {
    this._pendingUpdate.delete(component);

    this._rendering = component;
    this._rendering.hooks?.resetIndex();
    setHookState(this._getHookState);

    let output;
    try {
      output = (vnode.type as Function).call(null, vnode.props);
    } catch (err) {
      output = null;
      this._invokeErrorHandler(component, err);
    }

    this._rendering = null;
    setHookState(null);

    return output;
  }

  _invokeErrorHandler(context: Component, error: Error) {
    if (this._currentError) {
      // Only the first error in any render is reported.
      return;
    }

    let handled = false;
    let errorHandler = context as Component | null;
    while (errorHandler !== null) {
      try {
        const vnode = errorHandler.vnode;
        if (isErrorBoundary(vnode)) {
          vnode.props.handler(error);
          handled = true;
          break;
        }
      } catch (boundaryError) {
        error = boundaryError;
      }
      errorHandler = errorHandler.parent;
    }

    this._currentError = {
      error,
      handled,
    };
  }

  _scheduleEffects(component: Component, when: EffectTiming) {
    if (when === EffectTiming.afterRender) {
      const isScheduled = this._pendingEffects.size > 0;
      this._pendingEffects.add(component);
      if (!isScheduled) {
        // TODO - Use `requestAnimationFrame` or another method that will run
        // after rendering.
        queueMicrotask(() => this._flushEffects());
      }
    } else {
      const isScheduled = this._pendingLayoutEffects.size > 0;
      this._pendingLayoutEffects.add(component);
      if (!isScheduled) {
        queueMicrotask(() => this._flushLayoutEffects());
      }
    }
  }

  _flushLayoutEffects() {
    for (let component of this._pendingLayoutEffects) {
      component.hooks!.runEffects(EffectTiming.beforeRender);
    }
    this._pendingLayoutEffects.clear();
  }

  _flushEffects() {
    for (let component of this._pendingEffects) {
      component.hooks!.runEffects(EffectTiming.afterRender);
    }
    this._pendingEffects.clear();
  }

  _scheduleUpdate(component: Component) {
    const isScheduled = this._pendingUpdate.size > 0;
    this._pendingUpdate.add(component);
    if (!isScheduled) {
      queueMicrotask(() => this._flushUpdates());
    }
  }

  _flushUpdates() {
    // Flushing updates may trigger additional state changes. Therefore we loop
    // until there are no more pending updates.
    while (this._pendingUpdate.size > 0) {
      const pending = [...this._pendingUpdate];
      pending.sort((a, b) => a.depth - b.depth);

      for (let component of pending) {
        if (!this._pendingUpdate.has(component)) {
          // Component is a child of one higher up the tree that was already
          // re-rendered.
          continue;
        }

        let insertAfter = null as Node | null;

        let sibling = component;
        let parent = component.parent;
        while (parent) {
          const siblingIndex = parent.output.indexOf(sibling);
          for (let i = siblingIndex - 1; i >= 0 && !insertAfter; i--) {
            insertAfter = lastDomChild(parent.output[i]);
          }
          if (insertAfter || parent.dom) {
            break;
          }

          sibling = parent;
          parent = parent.parent;
        }

        let parentDom;
        if (insertAfter) {
          parentDom = insertAfter.parentElement as Element;
        } else if (parent?.dom) {
          parentDom = parent.dom as Element;
        } else {
          parentDom = this.container;
        }

        this._diff(
          component.parent,
          component,
          component.vnode,
          parentDom,
          insertAfter
        );
      }
    }

    this._handlePendingError();
  }

  /** Finish handling any pending error at the end of a render. */
  _handlePendingError() {
    if (!this._currentError) {
      return;
    }
    const lastError = this._currentError;
    this._currentError = null;

    if (!lastError.handled) {
      // Following React, unmount the entire tree if an error is uncaught:
      // https://reactjs.org/docs/error-boundaries.html#new-behavior-for-uncaught-errors
      this.render(null);
      throw lastError.error;
    }
  }

  _unmount(component: Component, isUnmountingAncestor = false) {
    if (isValidElement(component.vnode)) {
      // Run cleanup that only applies to DOM and custom components.
      for (let child of component.output) {
        this._unmount(child, true);
      }

      // Clear component ref. We only do this if the ref refers to the DOM element
      // being removed in case the same ref has been used for a new component mounted
      // in place of this one.
      const ref = component.vnode.ref;
      if (ref && ref.current === component.dom) {
        ref.current = null;
      }

      // Run cleanup that only applies to custom components.
      if (typeof component.vnode.type === "function") {
        this._pendingUpdate.delete(component);
        this._pendingEffects.delete(component);
        this._pendingLayoutEffects.delete(component);
        component.hooks?.cleanup();
      }
    }

    if (!isUnmountingAncestor) {
      forEachDomRoot(component, (node) => node.remove());
    }
  }
}

/**
 * Return all the `Root`s for currently mounted component trees.
 */
export function getRoots() {
  return activeRoots.values();
}

/**
 * Render a VNode into a DOM element
 *
 * See https://reactjs.org/docs/react-dom.html#render.
 */
export function render(vnode: VNodeChild, container: Element) {
  const root = activeRoots.get(container) ?? new Root(container);
  root.render(vnode);
}

/**
 * Return a `BaseComponent` tree describing the currently rendered content
 * inside a container element.
 */
export function getRenderedOutput(container: Element): BaseComponent | null {
  const root = activeRoots.get(container);
  if (!root) {
    return null;
  }
  return root.getOutput();
}

/**
 * Flush pending state updates and effects in a specific root.
 */
export function flushRoot(container: Element) {
  const root = activeRoots.get(container);
  if (root) {
    root.flush();
  }
}

/**
 * Remove any rendered component from a DOM element and clean up any associated
 * state.
 */
export function unmountComponentAtNode(container: Element) {
  const root = activeRoots.get(container);
  if (!root) {
    return false;
  }
  root.unmount();
  return true;
}
